chore: update pre-commit configuration and enhance GitHub Actions workflows
- Commented out the Zizmor pre-commit hook in `.pre-commit-config.yaml` to prevent its execution.
- Added a new `lint-gh-actions` target in the `Makefile` for running Zizmor with GitHub token.
- Introduced a new `zizmor.yml` configuration file for Zizmor, defining security audit rules and policies for action references.
- Created a new `.github/actionlint.yaml` file for configuring Actionlint to ignore specific shellcheck errors.
- Updated GitHub Actions workflows to include permissions for security events and actions, and to utilize the new Zizmor configuration.

These changes improve the security auditing process and streamline the CI/CD pipeline by integrating Zizmor and Actionlint effectively.

diff --git a/.github/workflows/tests-e2e.yml b/.github/workflows/tests-e2e.yml
--- a/.github/workflows/tests-e2e.yml
+++ b/.github/workflows/tests-e2e.yml
@@ -1,5 +1,7 @@
 # tests.yml
 name: CI-E2E
+permissions:
+  contents: read
 on:
   push:
     branches:
@@ -26,6 +28,9 @@ on:
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number|| github.sha }}
   cancel-in-progress: true
+env:
+  REGISTRY: ghcr.io
+  REGISTRY_IMAGE: ${{ github.repository_owner }}/zsh-dotfiles-prep
 
 jobs:
   style:
@@ -253,6 +258,9 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          persist-credentials: false
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
@@ -311,6 +319,9 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          persist-credentials: false
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -324,7 +335,13 @@ jobs:
 
       - name: Create merged manifest
         run: |
-          # Create a merged manifest with all platforms/images
+          echo "Validate registry image name"
+          if [[ "${{ env.REGISTRY_IMAGE }}" =~ [^a-zA-Z0-9_\-\.] ]]; then
+            echo "Invalid registry image name"
+            exit 1
+          fi
+
+          echo "Create a merged manifest with all platforms/images"
           docker buildx imagetools create \
             -t ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}:latest \
             ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}:debian-12 \
